const baseballCaps = [
  {
    categoryId: "1",
    name: "Classic Baseball Cap",
    slug: "classic-baseball-cap",
    price: 19.49,
    image: "https://picsum.photos/id/1011/500/500",
    stock: 8,
    description: {
      en: "A timeless classic baseball cap suitable for all occasions.",
      nl: "Een tijdloze klassieke baseballpet geschikt voor alle gelegenheden.",
      it: "Un cappellino da baseball classico senza tempo adatto a tutte le occasioni.",
    },
  },
  {
    categoryId: "1",
    name: "Snapback Baseball Cap",
    slug: "snapback-baseball-cap",
    price: 25.99,
    image: "https://picsum.photos/id/1012/500/500",
    stock: 5,
    description: {
      en: "A trendy snapback baseball cap with adjustable strap.",
      nl: "Een trendy snapback baseballpet met verstelbare band.",
      it: "Un cappellino da baseball snapback alla moda con cinturino regolabile.",
    },
  },
  {
    categoryId: "1",
    name: "Trucker Baseball Cap",
    slug: "trucker-baseball-cap",
    price: 22.59,
    image: "https://picsum.photos/id/1013/500/500",
    stock: 7,
    description: {
      en: "Stylish trucker baseball cap with mesh back for better ventilation.",
      nl: "Stijlvolle trucker baseballpet met mesh achterkant voor betere ventilatie.",
      it: "Stiloso cappellino da baseball da camionista con retro in mesh per una migliore ventilazione.",
    },
  },
  {
    categoryId: "1",
    name: "Dad Baseball Hat",
    slug: "dad-baseball-hat",
    price: 17.89,
    image: "https://picsum.photos/id/1014/500/500",
    stock: 4,
    description: {
      en: "Comfortable dad baseball hat perfect for casual wear.",
      nl: "Comfortabele vader baseballpet perfect voor casual wear.",
      it: "Comoda cappellino da baseball da papà perfetto per l'abbigliamento casual.",
    },
  },
  {
    categoryId: "1",
    name: "Beanie Baseball Cap",
    slug: "beanie-baseball-cap",
    price: 15.29,
    image: "https://picsum.photos/id/1015/500/500",
    stock: 6,
    description: {
      en: "Warm and cozy beanie baseball cap for chilly days.",
      nl: "Warm en gezellig beanie baseballpet voor koude dagen.",
      it: "Cappellino da baseball caldo e accogliente per le giornate fredde.",
    },
  },
  {
    categoryId: "1",
    name: "Sun Baseball Cap",
    slug: "sun-baseball-cap",
    price: 16.49,
    image: "https://picsum.photos/id/1016/500/500",
    stock: 9,
    description: {
      en: "Lightweight sun baseball cap for protection from the sun.",
      nl: "Lichtgewicht zonnebaseballpet voor bescherming tegen de zon.",
      it: "Cappellino da baseball leggero per protezione dal sole.",
    },
  },
  {
    categoryId: "1",
    name: "Sporty Baseball Cap",
    slug: "sporty-baseball-cap",
    price: 20.79,
    image: "https://picsum.photos/id/1017/500/500",
    stock: 7,
    description: {
      en: "Classic sporty baseball cap for sports and casual wear.",
      nl: "Klassieke sportieve baseballpet voor sport en l'abbigliamento casual.",
      it: "Cappellino da baseball sportivo classico per lo sport e l'abbigliamento casual.",
    },
  },
  {
    categoryId: "1",
    name: "Flat Baseball Cap",
    slug: "flat-baseball-cap",
    price: 26.59,
    image: "https://picsum.photos/id/1018/500/500",
    stock: 3,
    description: {
      en: "Stylish flat baseball cap for a sophisticated look.",
      nl: "Stijlvolle platte baseballpet voor een verfijnde uitstraling.",
      it: "Stiloso cappellino da baseball piatto per un look sofisticato.",
    },
  },
  {
    categoryId: "1",
    name: "Golf Baseball Cap",
    slug: "golf-baseball-cap",
    price: 21.99,
    image: "https://picsum.photos/id/1019/500/500",
    stock: 8,
    description: {
      en: "Comfortable golf baseball cap for outdoor activities.",
      nl: "Comfortabele golf baseballpet voor buitenactiviteiten.",
      it: "Comodo cappellino da baseball da golf per attività all'aperto.",
    },
  },
  {
    categoryId: "1",
    name: "Army Baseball Cap",
    slug: "army-baseball-cap",
    price: 23.49,
    image: "https://picsum.photos/id/1020/500/500",
    stock: 5,
    description: {
      en: "Durable army baseball cap for a rugged style.",
      nl: "Duurzame legerbaseballpet voor een ruige stijl.",
      it: "Durevole cappellino da baseball dell'esercito per uno stile robusto.",
    },
  },
  {
    categoryId: "1",
    name: "Performance Baseball Cap",
    slug: "performance-baseball-cap",
    price: 18.79,
    image: "https://picsum.photos/id/1021/500/500",
    stock: 6,
    description: {
      en: "Performance baseball cap for active wear.",
      nl: "Prestatiebaseballpet voor actieve slijtage.",
      it: "Cappellino da baseball da prestazione per l'abbigliamento attivo.",
    },
  },
  {
    categoryId: "1",
    name: "Newsboy Baseball Cap",
    slug: "newsboy-baseball-cap",
    price: 27.89,
    image: "https://picsum.photos/id/1022/500/500",
    stock: 4,
    description: {
      en: "Vintage newsboy baseball cap for a classic look.",
      nl: "Vintage newsboy baseballpet voor een klassieke uitstraling.",
      it: "Cappellino da baseball da ragazzo di giornale d'epoca per un look classico.",
    },
  },
  {
    categoryId: "1",
    name: "Visor Baseball Cap",
    slug: "visor-baseball-cap",
    price: 17.99,
    image: "https://picsum.photos/id/1023/500/500",
    stock: 9,
    description: {
      en: "Open-top visor baseball cap for sun protection.",
      nl: "Open-top zonneklep baseballpet voor bescherming tegen de zon.",
      it: "Cappellino da baseball con visiera aperta per protezione solare.",
    },
  },
  {
    categoryId: "1",
    name: "Bucket Baseball Hat",
    slug: "bucket-baseball-hat",
    price: 19.29,
    image: "https://picsum.photos/id/1024/500/500",
    stock: 5,
    description: {
      en: "Casual bucket baseball hat for a relaxed style.",
      nl: "Casual emmer baseballpet voor een ontspannen stijl.",
      it: "Cappellino da baseball a secchiello casual per uno stile rilassato.",
    },
  },
  {
    categoryId: "1",
    name: "Fashion Baseball Cap",
    slug: "fashion-baseball-cap",
    price: 28.99,
    image: "https://picsum.photos/id/1025/500/500",
    stock: 7,
    description: {
      en: "Trendy fashion baseball cap to elevate your outfit.",
      nl: "Trendy modebaseballpet om je outfit te verheffen.",
      it: "Cappellino da baseball alla moda per elevare il tuo outfit.",
    },
  },
  {
    categoryId: "1",
    name: "Mesh Baseball Cap",
    slug: "mesh-baseball-cap",
    price: 20.99,
    image: "https://picsum.photos/id/1026/500/500",
    stock: 6,
    description: {
      en: "Breathable mesh baseball cap for ultimate comfort.",
      nl: "Ademende mesh baseballpet voor ultiem comfort.",
      it: "Cappellino da baseball in mesh traspirante per un comfort ottimale.",
    },
  },
  {
    categoryId: "1",
    name: "Camouflage Baseball Cap",
    slug: "camouflage-baseball-cap",
    price: 22.79,
    image: "https://picsum.photos/id/1027/500/500",
    stock: 3,
    description: {
      en: "Stylish camouflage baseball cap for outdoor adventures.",
      nl: "Stijlvolle camouflage baseballpet voor buitenavonturen.",
      it: "Stiloso cappellino da baseball mimetico per avventure all'aperto.",
    },
  },
  {
    categoryId: "1",
    name: "Painter's Baseball Cap",
    slug: "painters-baseball-cap",
    price: 24.49,
    image: "https://picsum.photos/id/1028/500/500",
    stock: 8,
    description: {
      en: "Classic painter's baseball cap for artistic flair.",
      nl: "Klassieke schildersbaseballpet voor artistieke flair.",
      it: "Cappellino da baseball classico del pittore per un tocco artistico.",
    },
  },
  {
    categoryId: "1",
    name: "Cycling Baseball Cap",
    slug: "cycling-baseball-cap",
    price: 16.59,
    image: "https://picsum.photos/id/1029/500/500",
    stock: 7,
    description: {
      en: "Lightweight cycling baseball cap for biking enthusiasts.",
      nl: "Lichtgewicht fietsen baseballpet voor fietsliefhebbers.",
      it: "Cappellino da baseball leggero per appassionati di ciclismo.",
    },
  },
  {
    categoryId: "1",
    name: "Leather Baseball Cap",
    slug: "leather-baseball-cap",
    price: 30.99,
    image: "https://picsum.photos/id/1030/500/500",
    stock: 5,
    description: {
      en: "Luxurious leather baseball cap for a premium look.",
      nl: "Luxe leren baseballpet voor een premium uitstraling.",
      it: "Cappellino da baseball in pelle di lusso per un look premium.",
    },
  },
  {
    categoryId: "1",
    name: "Winter Baseball Cap",
    slug: "winter-baseball-cap",
    price: 15.89,
    image: "https://picsum.photos/id/1031/500/500",
    stock: 6,
    description: {
      en: "Warm winter baseball cap for cold weather.",
      nl: "Warme winter baseballpet voor koud weer.",
      it: "Cappellino da baseball invernale caldo per il freddo.",
    },
  },
  {
    categoryId: "1",
    name: "Promotional Baseball Cap",
    slug: "promotional-baseball-cap",
    price: 11.99,
    image: "https://picsum.photos/id/1032/500/500",
    stock: 9,
    description: {
      en: "Affordable promotional baseball cap for events.",
      nl: "Betaalbare promotionele baseballpet voor evenementen.",
      it: "Cappellino da baseball promozionale conveniente per eventi.",
    },
  },
  {
    categoryId: "1",
    name: "Festival Baseball Cap",
    slug: "festival-baseball-cap",
    price: 19.49,
    image: "https://picsum.photos/id/1033/500/500",
    stock: 4,
    description: {
      en: "Colorful festival baseball cap for fun occasions.",
      nl: "Kleurrijke festival baseballpet voor leuke gelegenheden.",
      it: "Cappellino da baseball colorato per occasioni divertenti.",
    },
  },
  {
    categoryId: "1",
    name: "Eco-Friendly Baseball Cap",
    slug: "eco-friendly-baseball-cap",
    price: 22.79,
    image: "https://picsum.photos/id/1034/500/500",
    stock: 7,
    description: {
      en: "Sustainable eco-friendly baseball cap.",
      nl: "Duurzame milieuvriendelijke baseballpet.",
      it: "Cappellino da baseball sostenibile e ecologico.",
    },
  },
  {
    categoryId: "1",
    name: "Travel Baseball Cap",
    slug: "travel-baseball-cap",
    price: 21.59,
    image: "https://picsum.photos/id/1035/500/500",
    stock: 6,
    description: {
      en: "Convenient travel baseball cap for on-the-go use.",
      nl: "Handige reisbaseballpet voor onderweg.",
      it: "Cappellino da baseball da viaggio comodo per l'uso in movimento.",
    },
  },
  {
    categoryId: "1",
    name: "Embroidered Baseball Cap",
    slug: "embroidered-baseball-cap",
    price: 24.99,
    image: "https://picsum.photos/id/1036/500/500",
    stock: 5,
    description: {
      en: "Elegant embroidered baseball cap for a unique style.",
      nl: "Elegante geborduurde baseballpet voor een unieke stijl.",
      it: "Cappellino da baseball ricamato elegante per uno stile unico.",
    },
  },
  {
    categoryId: "1",
    name: "Sequin Baseball Cap",
    slug: "sequin-baseball-cap",
    price: 26.79,
    image: "https://picsum.photos/id/1037/500/500",
    stock: 3,
    description: {
      en: "Sparkling sequin baseball cap for a glamorous look.",
      nl: "Schitterende pailletten baseballpet voor een glamoureuze uitstraling.",
      it: "Cappellino da baseball luccicante con paillettes per un look glamour.",
    },
  },
  {
    categoryId: "1",
    name: "Vintage Baseball Cap",
    slug: "vintage-baseball-cap",
    price: 27.99,
    image: "https://picsum.photos/id/1038/500/500",
    stock: 8,
    description: {
      en: "Retro vintage baseball cap for a nostalgic feel.",
      nl: "Retro vintage baseballpet voor een nostalgisch gevoel.",
      it: "Cappellino da baseball vintage retrò per una sensazione nostalgica.",
    },
  },
  {
    categoryId: "1",
    name: "Sports Team Baseball Cap",
    slug: "sports-team-baseball-cap",
    price: 23.79,
    image: "https://picsum.photos/id/1039/500/500",
    stock: 7,
    description: {
      en: "Support your favorite team with this baseball cap.",
      nl: "Steun je favoriete team met deze baseballpet.",
      it: "Sostieni la tua squadra preferita con questo cappellino da baseball.",
    },
  },
  {
    categoryId: "1",
    name: "Reflective Baseball Cap",
    slug: "reflective-baseball-cap",
    price: 25.49,
    image: "https://picsum.photos/id/1040/500/500",
    stock: 5,
    description: {
      en: "Stay visible with this reflective baseball cap.",
      nl: "Blijf zichtbaar met deze reflecterende baseballpet.",
      it: "Rimani visibile con questo cappellino da baseball riflettente.",
    },
  },
  {
    categoryId: "1",
    name: "Denim Baseball Cap",
    slug: "denim-baseball-cap",
    price: 20.99,
    image: "https://picsum.photos/id/1041/500/500",
    stock: 4,
    description: {
      en: "Stylish denim baseball cap for a casual look.",
      nl: "Stijlvolle denim baseballpet voor een casual look.",
      it: "Cappellino da baseball in denim alla moda per un look casual.",
    },
  },
  {
    categoryId: "1",
    name: "Logo Baseball Cap",
    slug: "logo-baseball-cap",
    price: 22.59,
    image: "https://picsum.photos/id/1042/500/500",
    stock: 6,
    description: {
      en: "Branded logo baseball cap for brand enthusiasts.",
      nl: "Merklogo baseballpet voor merkliefhebbers.",
      it: "Cappellino da baseball con logo di marca per gli appassionati di marca.",
    },
  },
  {
    categoryId: "1",
    name: "Military Baseball Cap",
    slug: "military-baseball-cap",
    price: 24.79,
    image: "https://picsum.photos/id/1043/500/500",
    stock: 9,
    description: {
      en: "Rugged military baseball cap for a tough style.",
      nl: "Stoere militaire baseballpet voor een ruige stijl.",
      it: "Cappellino da baseball militare resistente per uno stile duro.",
    },
  },
  {
    categoryId: "1",
    name: "Fitted Baseball Cap",
    slug: "fitted-baseball-cap",
    price: 22.99,
    image: "https://picsum.photos/id/1044/500/500",
    stock: 7,
    description: {
      en: "Perfectly fitted baseball cap for a snug fit.",
      nl: "Perfect passende baseballpet voor een strakke pasvorm.",
      it: "Cappellino da baseball perfettamente aderente per una vestibilità comoda.",
    },
  },
  {
    categoryId: "1",
    name: "Graphic Baseball Cap",
    slug: "graphic-baseball-cap",
    price: 23.99,
    image: "https://picsum.photos/id/1045/500/500",
    stock: 6,
    description: {
      en: "Bold graphic baseball cap for a standout look.",
      nl: "Gedurfd grafisch baseballpet voor een opvallende look.",
      it: "Cappellino da baseball grafico audace per un look eccezionale.",
    },
  },
  {
    categoryId: "1",
    name: "Mesh Back Baseball Cap",
    slug: "mesh-back-baseball-cap",
    price: 25.99,
    image: "https://picsum.photos/id/1046/500/500",
    stock: 5,
    description: {
      en: "Cool and breathable mesh back baseball cap.",
      nl: "Koel en ademend mesh achterkant baseballpet.",
    },
  },
  {
    categoryId: "1",
    name: "Patterned Baseball Cap",
    slug: "patterned-baseball-cap",
    price: 26.79,
    image: "https://picsum.photos/id/1047/500/500",
    stock: 4,
    description: {
      en: "Eye-catching patterned baseball cap for unique style.",
      nl: "Oogstrelende gestreepte baseballpet voor een unieke stijl.",
      it: "Cappellino da baseball a righe accattivante per uno stile unico.",
    },
  },
  {
    categoryId: "1",
    name: "Striped Baseball Cap",
    slug: "striped-baseball-cap",
    price: 20.79,
    image: "https://picsum.photos/id/1048/500/500",
    stock: 8,
    description: {
      en: "Striped baseball cap for a modern look.",
      nl: "Gestreepte baseballpet voor een moderne look.",
      it: "Cappellino da baseball a righe per un look moderno.",
    },
  },
  {
    categoryId: "1",
    name: "Leather Patch Baseball Cap",
    slug: "leather-patch-baseball-cap",
    price: 23.99,
    image: "https://picsum.photos/id/1049/500/500",
    stock: 7,
    description: {
      en: "Stylish baseball cap with a leather patch.",
      nl: "Stijlvolle baseballpet met een leren patch.",
      it: "Cappellino da baseball stiloso con un patch di pelle.",
    },
  },
  {
    categoryId: "1",
    name: "Corduroy Baseball Cap",
    slug: "corduroy-baseball-cap",
    price: 27.99,
    image: "https://picsum.photos/id/1050/500/500",
    stock: 5,
    description: {
      en: "Vintage corduroy baseball cap for a timeless style.",
      nl: "Vintage corduroy baseballpet voor een tijdloze stijl.",
      it: "Cappellino da baseball in corduroy vintage per uno stile senza tempo.",
    },
  },
  {
    categoryId: "1",
    name: "Plaid Baseball Cap",
    slug: "plaid-baseball-cap",
    price: 23.99,
    image: "https://picsum.photos/id/1051/500/500",
    stock: 6,
    description: {
      en: "Classic plaid baseball cap for a traditional look.",
      nl: "Klassieke plaid baseballpet voor een traditionele look.",
      it: "Cappellino da baseball in plaid classico per un look tradizionale.",
    },
  },
  {
    categoryId: "1",
    name: "Nylon Baseball Cap",
    slug: "nylon-baseball-cap",
    price: 21.99,
    image: "https://picsum.photos/id/1052/500/500",
    stock: 3,
    description: {
      en: "Lightweight nylon baseball cap perfect for outdoor activities.",
      nl: "Lichtgewicht nylon baseballpet perfect voor buitensporten.",
      it: "Cappellino da baseball in nylon leggero perfetto per le attività all'aperto.",
    },
  },
  {
    categoryId: "1",
    name: "Suede Baseball Cap",
    slug: "suede-baseball-cap",
    price: 29.99,
    image: "https://picsum.photos/id/1053/500/500",
    stock: 5,
    description: {
      en: "Luxurious suede baseball cap for a premium feel.",
      nl: "Luxueuze suede baseballpet voor een premium gevoel.",
      it: "Cappellino da baseball in suede lussuoso per un feel premium.",
    },
  },
  {
    categoryId: "1",
    name: "Faux Fur Baseball Cap",
    slug: "faux-fur-baseball-cap",
    price: 28.99,
    image: "https://picsum.photos/id/1054/500/500",
    stock: 9,
    description: {
      en: "Warm and stylish faux fur baseball cap.",
      nl: "Warm en stijlvolle nepbont baseballpet.",
      it: "Cappellino da baseball in finta pelliccia caldo e stiloso.",
    },
  },
  {
    categoryId: "1",
    name: "Racing Baseball Cap",
    slug: "racing-baseball-cap",
    price: 25.99,
    image: "https://picsum.photos/id/1055/500/500",
    stock: 7,
    description: {
      en: "Dynamic racing baseball cap for speed enthusiasts.",
      nl: "Dynamische racing baseballpet voor snelheidsliefhebbers.",
      it: "Cappellino da baseball da corsa dinamico per appassionati di velocità.",
    },
  },
  {
    categoryId: "1",
    name: "Hiking Baseball Cap",
    slug: "hiking-baseball-cap",
    price: 23.49,
    image: "https://picsum.photos/id/1056/500/500",
    stock: 4,
    description: {
      en: "Durable hiking baseball cap for outdoor adventures.",
      nl: "Duurzame hiking baseballpet voor buitensporten.",
      it: "Cappellino da baseball da hiking resistente per avventure all'aperto.",
    },
  },
  {
    categoryId: "1",
    name: "Gardening Baseball Cap",
    slug: "gardening-baseball-cap",
    price: 21.59,
    image: "https://picsum.photos/id/1057/500/500",
    stock: 6,
    description: {
      en: "Functional gardening baseball cap for garden lovers.",
      nl: "Functionele gardening baseballpet voor tuinliefhebbers.",
      it: "Cappellino da baseball da giardinaggio funzionale per amanti del giardino.",
    },
  },
  {
    categoryId: "1",
    name: "Cooking Baseball Cap",
    slug: "cooking-baseball-cap",
    price: 19.89,
    image: "https://picsum.photos/id/1058/500/500",
    stock: 5,
    description: {
      en: "Practical cooking baseball cap for culinary enthusiasts.",
      nl: "Praktische cooking baseballpet voor culinaire enthousiastelingen.",
      it: "Cappellino da baseball da cucina pratico per appassionati di cucina.",
    },
  },
  {
    categoryId: "1",
    name: "Fishing Baseball Cap",
    slug: "fishing-baseball-cap",
    price: 22.99,
    image: "https://picsum.photos/id/1059/500/500",
    stock: 3,
    description: {
      en: "Comfortable fishing baseball cap for fishing trips.",
      nl: "Comfortabele fishing baseballpet voor visreizen.",
      it: "Cappellino da baseball da pesca comodo per viaggi di pesca.",
    },
  },
  {
    categoryId: "1",
    name: "Ski Baseball Cap",
    slug: "ski-baseball-cap",
    price: 24.99,
    image: "https://picsum.photos/id/1060/500/500",
    stock: 8,
    description: {
      en: "Warm ski baseball cap for winter sports.",
      nl: "Warm ski baseballpet voor wintersporten.",
      it: "Cappellino da baseball da sci caldo per sport invernali.",
    },
  },
];

export { baseballCaps };
