const baseballCaps = [
  {
    categoryId: "1",
    name: "Classic Baseball Cap",
    price: 19.49,
    image: "https://picsum.photos/id/1011/500/500",
    stock: 8,
    description: "A timeless classic baseball cap suitable for all occasions.",
  },
  {
    categoryId: "1",
    name: "Snapback Baseball Cap",
    price: 25.99,
    image: "https://picsum.photos/id/1012/500/500",
    stock: 5,
    description: "A trendy snapback baseball cap with adjustable strap.",
  },
  {
    categoryId: "1",
    name: "Trucker Baseball Cap",
    price: 22.59,
    image: "https://picsum.photos/id/1013/500/500",
    stock: 7,
    description:
      "Stylish trucker baseball cap with mesh back for better ventilation.",
  },
  {
    categoryId: "1",
    name: "Dad Baseball Hat",
    price: 17.89,
    image: "https://picsum.photos/id/1014/500/500",
    stock: 4,
    description: "Comfortable dad baseball hat perfect for casual wear.",
  },
  {
    categoryId: "1",
    name: "Beanie Baseball Cap",
    price: 15.29,
    image: "https://picsum.photos/id/1015/500/500",
    stock: 6,
    description: "Warm and cozy beanie baseball cap for chilly days.",
  },
  {
    categoryId: "1",
    name: "Sun Baseball Cap",
    price: 16.49,
    image: "https://picsum.photos/id/1016/500/500",
    stock: 9,
    description: "Lightweight sun baseball cap for protection from the sun.",
  },
  {
    categoryId: "1",
    name: "Sporty Baseball Cap",
    price: 20.79,
    image: "https://picsum.photos/id/1017/500/500",
    stock: 7,
    description: "Classic sporty baseball cap for sports and casual wear.",
  },
  {
    categoryId: "1",
    name: "Flat Baseball Cap",
    price: 26.59,
    image: "https://picsum.photos/id/1018/500/500",
    stock: 3,
    description: "Stylish flat baseball cap for a sophisticated look.",
  },
  {
    categoryId: "1",
    name: "Golf Baseball Cap",
    price: 21.99,
    image: "https://picsum.photos/id/1019/500/500",
    stock: 8,
    description: "Comfortable golf baseball cap for outdoor activities.",
  },
  {
    categoryId: "1",
    name: "Army Baseball Cap",
    price: 23.49,
    image: "https://picsum.photos/id/1020/500/500",
    stock: 5,
    description: "Durable army baseball cap for a rugged style.",
  },
  {
    categoryId: "1",
    name: "Performance Baseball Cap",
    price: 18.79,
    image: "https://picsum.photos/id/1021/500/500",
    stock: 6,
    description: "Performance baseball cap for active wear.",
  },
  {
    categoryId: "1",
    name: "Newsboy Baseball Cap",
    price: 27.89,
    image: "https://picsum.photos/id/1022/500/500",
    stock: 4,
    description: "Vintage newsboy baseball cap for a classic look.",
  },
  {
    categoryId: "1",
    name: "Visor Baseball Cap",
    price: 17.99,
    image: "https://picsum.photos/id/1023/500/500",
    stock: 9,
    description: "Open-top visor baseball cap for sun protection.",
  },
  {
    categoryId: "1",
    name: "Bucket Baseball Hat",
    price: 19.29,
    image: "https://picsum.photos/id/1024/500/500",
    stock: 5,
    description: "Casual bucket baseball hat for a relaxed style.",
  },
  {
    categoryId: "1",
    name: "Fashion Baseball Cap",
    price: 28.99,
    image: "https://picsum.photos/id/1025/500/500",
    stock: 7,
    description: "Trendy fashion baseball cap to elevate your outfit.",
  },
  {
    categoryId: "1",
    name: "Mesh Baseball Cap",
    price: 20.99,
    image: "https://picsum.photos/id/1026/500/500",
    stock: 6,
    description: "Breathable mesh baseball cap for ultimate comfort.",
  },
  {
    categoryId: "1",
    name: "Camouflage Baseball Cap",
    price: 22.79,
    image: "https://picsum.photos/id/1027/500/500",
    stock: 3,
    description: "Stylish camouflage baseball cap for outdoor adventures.",
  },
  {
    categoryId: "1",
    name: "Painter's Baseball Cap",
    price: 24.49,
    image: "https://picsum.photos/id/1028/500/500",
    stock: 8,
    description: "Classic painter's baseball cap for artistic flair.",
  },
  {
    categoryId: "1",
    name: "Cycling Baseball Cap",
    price: 16.59,
    image: "https://picsum.photos/id/1029/500/500",
    stock: 7,
    description: "Lightweight cycling baseball cap for biking enthusiasts.",
  },
  {
    categoryId: "1",
    name: "Leather Baseball Cap",
    price: 30.99,
    image: "https://picsum.photos/id/1030/500/500",
    stock: 5,
    description: "Luxurious leather baseball cap for a premium look.",
  },
  {
    categoryId: "1",
    name: "Winter Baseball Cap",
    price: 15.89,
    image: "https://picsum.photos/id/1031/500/500",
    stock: 6,
    description: "Warm winter baseball cap for cold weather.",
  },
  {
    categoryId: "1",
    name: "Promotional Baseball Cap",
    price: 11.99,
    image: "https://picsum.photos/id/1032/500/500",
    stock: 9,
    description: "Affordable promotional baseball cap for events.",
  },
  {
    categoryId: "1",
    name: "Festival Baseball Cap",
    price: 19.49,
    image: "https://picsum.photos/id/1033/500/500",
    stock: 4,
    description: "Colorful festival baseball cap for fun occasions.",
  },
  {
    categoryId: "1",
    name: "Eco-Friendly Baseball Cap",
    price: 22.79,
    image: "https://picsum.photos/id/1034/500/500",
    stock: 7,
    description: "Sustainable eco-friendly baseball cap.",
  },
  {
    categoryId: "1",
    name: "Travel Baseball Cap",
    price: 21.59,
    image: "https://picsum.photos/id/1035/500/500",
    stock: 6,
    description: "Convenient travel baseball cap for on-the-go use.",
  },
  {
    categoryId: "1",
    name: "Embroidered Baseball Cap",
    price: 24.99,
    image: "https://picsum.photos/id/1036/500/500",
    stock: 5,
    description: "Elegant embroidered baseball cap for a unique style.",
  },
  {
    categoryId: "1",
    name: "Sequin Baseball Cap",
    price: 26.79,
    image: "https://picsum.photos/id/1037/500/500",
    stock: 3,
    description: "Sparkling sequin baseball cap for a glamorous look.",
  },
  {
    categoryId: "1",
    name: "Vintage Baseball Cap",
    price: 27.99,
    image: "https://picsum.photos/id/1038/500/500",
    stock: 8,
    description: "Retro vintage baseball cap for a nostalgic feel.",
  },
  {
    categoryId: "1",
    name: "Sports Team Baseball Cap",
    price: 23.79,
    image: "https://picsum.photos/id/1039/500/500",
    stock: 7,
    description: "Support your favorite team with this baseball cap.",
  },
  {
    categoryId: "1",
    name: "Reflective Baseball Cap",
    price: 25.49,
    image: "https://picsum.photos/id/1040/500/500",
    stock: 5,
    description: "Stay visible with this reflective baseball cap.",
  },
  {
    categoryId: "1",
    name: "Denim Baseball Cap",
    price: 20.99,
    image: "https://picsum.photos/id/1041/500/500",
    stock: 4,
    description: "Stylish denim baseball cap for a casual look.",
  },
  {
    categoryId: "1",
    name: "Logo Baseball Cap",
    price: 22.59,
    image: "https://picsum.photos/id/1042/500/500",
    stock: 6,
    description: "Branded logo baseball cap for brand enthusiasts.",
  },
  {
    categoryId: "1",
    name: "Military Baseball Cap",
    price: 24.79,
    image: "https://picsum.photos/id/1043/500/500",
    stock: 9,
    description: "Rugged military baseball cap for a tough style.",
  },
  {
    categoryId: "1",
    name: "Fitted Baseball Cap",
    price: 22.99,
    image: "https://picsum.photos/id/1044/500/500",
    stock: 7,
    description: "Perfectly fitted baseball cap for a snug fit.",
  },
  {
    categoryId: "1",
    name: "Graphic Baseball Cap",
    price: 23.99,
    image: "https://picsum.photos/id/1045/500/500",
    stock: 6,
    description: "Bold graphic baseball cap for a standout look.",
  },
  {
    categoryId: "1",
    name: "Mesh Back Baseball Cap",
    price: 25.99,
    image: "https://picsum.photos/id/1046/500/500",
    stock: 5,
    description: "Cool and breathable mesh back baseball cap.",
  },
  {
    categoryId: "1",
    name: "Patterned Baseball Cap",
    price: 26.79,
    image: "https://picsum.photos/id/1047/500/500",
    stock: 4,
    description: "Eye-catching patterned baseball cap for unique style.",
  },
  {
    categoryId: "1",
    name: "Striped Baseball Cap",
    price: 20.79,
    image: "https://picsum.photos/id/1048/500/500",
    stock: 8,
    description: "Striped baseball cap for a modern look.",
  },
  {
    categoryId: "1",
    name: "Leather Patch Baseball Cap",
    price: 23.99,
    image: "https://picsum.photos/id/1049/500/500",
    stock: 7,
    description: "Stylish baseball cap with a leather patch.",
  },
  {
    categoryId: "1",
    name: "Corduroy Baseball Cap",
    price: 27.99,
    image: "https://picsum.photos/id/1050/500/500",
    stock: 5,
    description: "Vintage corduroy baseball cap for a timeless style.",
  },
  {
    categoryId: "1",
    name: "Plaid Baseball Cap",
    price: 23.99,
    image: "https://picsum.photos/id/1051/500/500",
    stock: 6,
    description: "Classic plaid baseball cap for a traditional look.",
  },
  {
    categoryId: "1",
    name: "Nylon Baseball Cap",
    price: 21.99,
    image: "https://picsum.photos/id/1052/500/500",
    stock: 3,
    description:
      "Lightweight nylon baseball cap perfect for outdoor activities.",
  },
  {
    categoryId: "1",
    name: "Suede Baseball Cap",
    price: 29.99,
    image: "https://picsum.photos/id/1053/500/500",
    stock: 5,
    description: "Luxurious suede baseball cap for a premium feel.",
  },
  {
    categoryId: "1",
    name: "Faux Fur Baseball Cap",
    price: 28.99,
    image: "https://picsum.photos/id/1054/500/500",
    stock: 9,
    description: "Warm and stylish faux fur baseball cap.",
  },
  {
    categoryId: "1",
    name: "Racing Baseball Cap",
    price: 25.99,
    image: "https://picsum.photos/id/1055/500/500",
    stock: 7,
    description: "Dynamic racing baseball cap for speed enthusiasts.",
  },
  {
    categoryId: "1",
    name: "Hiking Baseball Cap",
    price: 23.49,
    image: "https://picsum.photos/id/1056/500/500",
    stock: 4,
    description: "Durable hiking baseball cap for outdoor adventures.",
  },
  {
    categoryId: "1",
    name: "Gardening Baseball Cap",
    price: 21.59,
    image: "https://picsum.photos/id/1057/500/500",
    stock: 6,
    description: "Functional gardening baseball cap for garden lovers.",
  },
  {
    categoryId: "1",
    name: "Cooking Baseball Cap",
    price: 19.89,
    image: "https://picsum.photos/id/1058/500/500",
    stock: 5,
    description: "Practical cooking baseball cap for culinary enthusiasts.",
  },
  {
    categoryId: "1",
    name: "Fishing Baseball Cap",
    price: 22.99,
    image: "https://picsum.photos/id/1059/500/500",
    stock: 3,
    description: "Comfortable fishing baseball cap for fishing trips.",
  },
  {
    categoryId: "1",
    name: "Ski Baseball Cap",
    price: 24.99,
    image: "https://picsum.photos/id/1060/500/500",
    stock: 8,
    description: "Warm ski baseball cap for winter sports.",
  },
];

export { baseballCaps };
