const caps = [
  {
    name: "Classic Cap",
    price: 19.49,
    image: "https://picsum.photos/id/1011/500/500",
    stock: 8,
    description: "A timeless classic cap suitable for all occasions.",
  },
  {
    name: "Snapback Cap",
    price: 25.99,
    image: "https://picsum.photos/id/1012/500/500",
    stock: 5,
    description: "A trendy snapback cap with adjustable strap.",
  },
  {
    name: "Trucker Cap",
    price: 22.59,
    image: "https://picsum.photos/id/1013/500/500",
    stock: 7,
    description: "Stylish trucker cap with mesh back for better ventilation.",
  },
  {
    name: "Dad Hat",
    price: 17.89,
    image: "https://picsum.photos/id/1014/500/500",
    stock: 4,
    description: "Comfortable dad hat perfect for casual wear.",
  },
  {
    name: "Beanie",
    price: 15.29,
    image: "https://picsum.photos/id/1015/500/500",
    stock: 6,
    description: "Warm and cozy beanie for chilly days.",
  },
  {
    name: "Sun Cap",
    price: 16.49,
    image: "https://picsum.photos/id/1016/500/500",
    stock: 9,
    description: "Lightweight sun cap for protection from the sun.",
  },
  {
    name: "Baseball Cap",
    price: 20.79,
    image: "https://picsum.photos/id/1017/500/500",
    stock: 7,
    description: "Classic baseball cap for sports and casual wear.",
  },
  {
    name: "Flat Cap",
    price: 26.59,
    image: "https://picsum.photos/id/1018/500/500",
    stock: 3,
    description: "Stylish flat cap for a sophisticated look.",
  },
  {
    name: "Golf Cap",
    price: 21.99,
    image: "https://picsum.photos/id/1019/500/500",
    stock: 8,
    description: "Comfortable golf cap for outdoor activities.",
  },
  {
    name: "Army Cap",
    price: 23.49,
    image: "https://picsum.photos/id/1020/500/500",
    stock: 5,
    description: "Durable army cap for a rugged style.",
  },
  {
    name: "Sports Cap",
    price: 18.79,
    image: "https://picsum.photos/id/1021/500/500",
    stock: 6,
    description: "Performance sports cap for active wear.",
  },
  {
    name: "Newsboy Cap",
    price: 27.89,
    image: "https://picsum.photos/id/1022/500/500",
    stock: 4,
    description: "Vintage newsboy cap for a classic look.",
  },
  {
    name: "Visor Cap",
    price: 17.99,
    image: "https://picsum.photos/id/1023/500/500",
    stock: 9,
    description: "Open-top visor cap for sun protection.",
  },
  {
    name: "Bucket Hat",
    price: 19.29,
    image: "https://picsum.photos/id/1024/500/500",
    stock: 5,
    description: "Casual bucket hat for a relaxed style.",
  },
  {
    name: "Fashion Cap",
    price: 28.99,
    image: "https://picsum.photos/id/1025/500/500",
    stock: 7,
    description: "Trendy fashion cap to elevate your outfit.",
  },
  {
    name: "Mesh Cap",
    price: 20.99,
    image: "https://picsum.photos/id/1026/500/500",
    stock: 6,
    description: "Breathable mesh cap for ultimate comfort.",
  },
  {
    name: "Camouflage Cap",
    price: 22.79,
    image: "https://picsum.photos/id/1027/500/500",
    stock: 3,
    description: "Stylish camouflage cap for outdoor adventures.",
  },
  {
    name: "Painter's Cap",
    price: 24.49,
    image: "https://picsum.photos/id/1028/500/500",
    stock: 8,
    description: "Classic painter's cap for artistic flair.",
  },
  {
    name: "Cycling Cap",
    price: 16.59,
    image: "https://picsum.photos/id/1029/500/500",
    stock: 7,
    description: "Lightweight cycling cap for biking enthusiasts.",
  },
  {
    name: "Leather Cap",
    price: 30.99,
    image: "https://picsum.photos/id/1030/500/500",
    stock: 5,
    description: "Luxurious leather cap for a premium look.",
  },
  {
    name: "Winter Cap",
    price: 15.89,
    image: "https://picsum.photos/id/1031/500/500",
    stock: 6,
    description: "Warm winter cap for cold weather.",
  },
  {
    name: "Promotional Cap",
    price: 11.99,
    image: "https://picsum.photos/id/1032/500/500",
    stock: 9,
    description: "Affordable promotional cap for events.",
  },
  {
    name: "Festival Cap",
    price: 19.49,
    image: "https://picsum.photos/id/1033/500/500",
    stock: 4,
    description: "Colorful festival cap for fun occasions.",
  },
  {
    name: "Eco-Friendly Cap",
    price: 22.79,
    image: "https://picsum.photos/id/1034/500/500",
    stock: 7,
    description: "Sustainable eco-friendly cap.",
  },
  {
    name: "Travel Cap",
    price: 21.59,
    image: "https://picsum.photos/id/1035/500/500",
    stock: 6,
    description: "Convenient travel cap for on-the-go use.",
  },
  {
    name: "Embroidered Cap",
    price: 24.99,
    image: "https://picsum.photos/id/1036/500/500",
    stock: 5,
    description: "Elegant embroidered cap for a unique style.",
  },
  {
    name: "Sequin Cap",
    price: 26.79,
    image: "https://picsum.photos/id/1037/500/500",
    stock: 3,
    description: "Sparkling sequin cap for a glamorous look.",
  },
  {
    name: "Vintage Cap",
    price: 27.99,
    image: "https://picsum.photos/id/1038/500/500",
    stock: 8,
    description: "Retro vintage cap for a nostalgic feel.",
  },
  {
    name: "Sports Team Cap",
    price: 23.79,
    image: "https://picsum.photos/id/1039/500/500",
    stock: 7,
    description: "Support your favorite team with this sports cap.",
  },
  {
    name: "Reflective Cap",
    price: 25.49,
    image: "https://picsum.photos/id/1040/500/500",
    stock: 5,
    description: "Stay visible with this reflective cap.",
  },
  {
    name: "Denim Cap",
    price: 20.99,
    image: "https://picsum.photos/id/1041/500/500",
    stock: 4,
    description: "Stylish denim cap for a casual look.",
  },
  {
    name: "Logo Cap",
    price: 22.59,
    image: "https://picsum.photos/id/1042/500/500",
    stock: 6,
    description: "Branded logo cap for brand enthusiasts.",
  },
  {
    name: "Military Cap",
    price: 24.79,
    image: "https://picsum.photos/id/1043/500/500",
    stock: 9,
    description: "Rugged military cap for a tough style.",
  },
  {
    name: "Fitted Cap",
    price: 22.99,
    image: "https://picsum.photos/id/1044/500/500",
    stock: 7,
    description: "Perfectly fitted cap for a snug fit.",
  },
  {
    name: "Graphic Cap",
    price: 23.99,
    image: "https://picsum.photos/id/1045/500/500",
    stock: 6,
    description: "Bold graphic cap for a standout look.",
  },
  {
    name: "Mesh Back Cap",
    price: 25.99,
    image: "https://picsum.photos/id/1046/500/500",
    stock: 5,
    description: "Cool and breathable mesh back cap.",
  },
  {
    name: "Patterned Cap",
    price: 26.79,
    image: "https://picsum.photos/id/1047/500/500",
    stock: 4,
    description: "Eye-catching patterned cap for unique style.",
  },
  {
    name: "Striped Cap",
    price: 20.79,
    image: "https://picsum.photos/id/1048/500/500",
    stock: 8,
    description: "Striped cap for a modern look.",
  },
  {
    name: "Leather Patch Cap",
    price: 23.99,
    image: "https://picsum.photos/id/1049/500/500",
    stock: 7,
    description: "Stylish cap with a leather patch.",
  },
  {
    name: "Corduroy Cap",
    price: 27.99,
    image: "https://picsum.photos/id/1050/500/500",
    stock: 5,
    description: "Vintage corduroy cap for a timeless style.",
  },
  {
    name: "Plaid Cap",
    price: 23.99,
    image: "https://picsum.photos/id/1051/500/500",
    stock: 6,
    description: "Classic plaid cap for a traditional look.",
  },
  {
    name: "Nylon Cap",
    price: 21.99,
    image: "https://picsum.photos/id/1052/500/500",
    stock: 3,
    description: "Lightweight nylon cap perfect for outdoor activities.",
  },
  {
    name: "Suede Cap",
    price: 29.99,
    image: "https://picsum.photos/id/1053/500/500",
    stock: 5,
    description: "Luxurious suede cap for a premium feel.",
  },
  {
    name: "Faux Fur Cap",
    price: 28.99,
    image: "https://picsum.photos/id/1054/500/500",
    stock: 9,
    description: "Warm and stylish faux fur cap.",
  },
  {
    name: "Racing Cap",
    price: 25.99,
    image: "https://picsum.photos/id/1055/500/500",
    stock: 7,
    description: "Dynamic racing cap for speed enthusiasts.",
  },
  {
    name: "Hiking Cap",
    price: 23.49,
    image: "https://picsum.photos/id/1056/500/500",
    stock: 4,
    description: "Durable hiking cap for outdoor adventures.",
  },
  {
    name: "Gardening Cap",
    price: 21.59,
    image: "https://picsum.photos/id/1057/500/500",
    stock: 6,
    description: "Functional gardening cap for garden lovers.",
  },
  {
    name: "Cooking Cap",
    price: 19.89,
    image: "https://picsum.photos/id/1058/500/500",
    stock: 5,
    description: "Practical cooking cap for culinary enthusiasts.",
  },
  {
    name: "Fishing Cap",
    price: 22.99,
    image: "https://picsum.photos/id/1059/500/500",
    stock: 3,
    description: "Comfortable fishing cap for fishing trips.",
  },
  {
    name: "Ski Cap",
    price: 24.99,
    image: "https://picsum.photos/id/1060/500/500",
    stock: 8,
    description: "Warm ski cap for winter sports.",
  },
];

export { caps };
