const sweaters = [
  {
    name: "Pullover Hoodie",
    price: 49.99,
    image: "https://picsum.photos/id/200/500/500",
    stock: 9,
    description: "Comfortable pullover hoodie great for everyday wear.",
  },
  {
    name: "Crewneck Sweatshirt",
    price: 39.89,
    image: "https://picsum.photos/id/201/500/500",
    stock: 3,
    description: "Classic crewneck sweatshirt with a relaxed fit.",
  },
  {
    name: "Zip-up Hoodie",
    price: 59.99,
    image: "https://picsum.photos/id/202/500/500",
    stock: 8,
    description: "Versatile zip-up hoodie for layering.",
  },
  {
    name: "Fleece Jacket",
    price: 69.49,
    image: "https://picsum.photos/id/203/500/500",
    stock: 5,
    description: "Warm fleece jacket ideal for outdoor activities.",
  },
  {
    name: "Wool Sweater",
    price: 89.99,
    image: "https://picsum.photos/id/204/500/500",
    stock: 6,
    description: "Elegant wool sweater for a sophisticated look.",
  },
  {
    name: "Knitted Sweater",
    price: 49.29,
    image: "https://picsum.photos/id/205/500/500",
    stock: 9,
    description: "Cozy knitted sweater for chilly days.",
  },
  {
    name: "Cashmere Sweater",
    price: 99.89,
    image: "https://picsum.photos/id/206/500/500",
    stock: 4,
    description: "Luxurious cashmere sweater for ultimate comfort.",
  },
  {
    name: "Cardigan",
    price: 59.79,
    image: "https://picsum.photos/id/207/500/500",
    stock: 7,
    description: "Classic cardigan sweater for a timeless look.",
  },
  {
    name: "V-neck Sweater",
    price: 44.99,
    image: "https://picsum.photos/id/208/500/500",
    stock: 8,
    description: "Stylish V-neck sweater for a casual style.",
  },
  {
    name: "Button-up Sweater",
    price: 54.89,
    image: "https://picsum.photos/id/209/500/500",
    stock: 5,
    description: "Elegant button-up sweater for formal occasions.",
  },
  {
    name: "Turtleneck Sweater",
    price: 64.49,
    image: "https://picsum.photos/id/210/500/500",
    stock: 3,
    description: "Warm turtleneck sweater for cold weather.",
  },
  {
    name: "Mock Neck Sweater",
    price: 59.29,
    image: "https://picsum.photos/id/211/500/500",
    stock: 6,
    description: "Trendy mock neck sweater for a modern look.",
  },
  {
    name: "Cowl Neck Sweater",
    price: 69.99,
    image: "https://picsum.photos/id/212/500/500",
    stock: 7,
    description: "Cozy cowl neck sweater for ultimate warmth.",
  },
  {
    name: "Roll Neck Sweater",
    price: 64.79,
    image: "https://picsum.photos/id/213/500/500",
    stock: 4,
    description: "Classic roll neck sweater for a sophisticated style.",
  },
  {
    name: "Chunky Knit Sweater",
    price: 79.49,
    image: "https://picsum.photos/id/214/500/500",
    stock: 5,
    description: "Thick and warm chunky knit sweater.",
  },
  {
    name: "Cable Knit Sweater",
    price: 74.59,
    image: "https://picsum.photos/id/215/500/500",
    stock: 6,
    description: "Classic cable knit sweater for a timeless look.",
  },
  {
    name: "Fair Isle Sweater",
    price: 89.89,
    image: "https://picsum.photos/id/216/500/500",
    stock: 7,
    description: "Colorful Fair Isle sweater for a festive style.",
  },
  {
    name: "Sweater Vest",
    price: 39.99,
    image: "https://picsum.photos/id/217/500/500",
    stock: 3,
    description: "Trendy sweater vest for layering.",
  },
  {
    name: "Shawl Collar Sweater",
    price: 69.49,
    image: "https://picsum.photos/id/218/500/500",
    stock: 8,
    description: "Stylish shawl collar sweater for added warmth.",
  },
  {
    name: "Henley Sweater",
    price: 54.29,
    image: "https://picsum.photos/id/219/500/500",
    stock: 6,
    description: "Casual Henley sweater for a laid-back look.",
  },
  {
    name: "Sweater Dress",
    price: 79.59,
    image: "https://picsum.photos/id/220/500/500",
    stock: 5,
    description: "Elegant sweater dress for a chic style.",
  },
  {
    name: "Off Shoulder Sweater",
    price: 59.99,
    image: "https://picsum.photos/id/221/500/500",
    stock: 4,
    description: "Fashionable off-shoulder sweater for a trendy look.",
  },
  {
    name: "Asymmetrical Sweater",
    price: 64.79,
    image: "https://picsum.photos/id/222/500/500",
    stock: 7,
    description: "Unique asymmetrical sweater for a modern style.",
  },
  {
    name: "Ribbed Sweater",
    price: 49.99,
    image: "https://picsum.photos/id/223/500/500",
    stock: 6,
    description: "Classic ribbed sweater for a comfortable fit.",
  },
  {
    name: "Oversized Sweater",
    price: 69.49,
    image: "https://picsum.photos/id/224/500/500",
    stock: 5,
    description: "Cozy oversized sweater for a relaxed look.",
  },
  {
    name: "Fringe Sweater",
    price: 74.89,
    image: "https://picsum.photos/id/225/500/500",
    stock: 3,
    description: "Stylish fringe sweater for a trendy style.",
  },
  {
    name: "Sequin Sweater",
    price: 84.99,
    image: "https://picsum.photos/id/226/500/500",
    stock: 7,
    description: "Sparkling sequin sweater for special occasions.",
  },
  {
    name: "Metallic Sweater",
    price: 79.59,
    image: "https://picsum.photos/id/227/500/500",
    stock: 6,
    description: "Shiny metallic sweater for a bold look.",
  },
  {
    name: "Color Block Sweater",
    price: 69.89,
    image: "https://picsum.photos/id/228/500/500",
    stock: 8,
    description: "Trendy color block sweater for a vibrant style.",
  },
  {
    name: "Striped Sweater",
    price: 59.99,
    image: "https://picsum.photos/id/229/500/500",
    stock: 5,
    description: "Classic striped sweater for a casual look.",
  },
];

export { sweaters };
